package lib.ballistic;

import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;

public class CommonLookupTable {
    public record ShotTable (
        /** Meters away from hub to hood angle in radians */
        InterpolatingDoubleTreeMap hoodAngle,
        /** Meters away from hub to flywheel speed in radians per second */
        InterpolatingDoubleTreeMap flywheelSpeed,
        /** Time in seconds to shoot to the hub based on distance in meters */
        InterpolatingDoubleTreeMap timeOfFlight
    ) {
        public ShotTable() {
            this(new InterpolatingDoubleTreeMap(), new InterpolatingDoubleTreeMap(), new InterpolatingDoubleTreeMap());
        }
    }

    /** Table containing shooting params for the hub */
    public static final ShotTable hubTable = new ShotTable();
    /** Table containing shooting params for passing */
    public static final ShotTable passingTable = new ShotTable();
    
    static {
        /* *****HUB***** */
        hubTable.hoodAngle.put(1.0, 0.0);
        hubTable.hoodAngle.put(2.0, 0.05);
        hubTable.hoodAngle.put(3.0, 0.09);
        hubTable.hoodAngle.put(4.0, 0.12);
        hubTable.hoodAngle.put(5.0, 0.15);
        hubTable.hoodAngle.put(6.0, 0.2);
        hubTable.hoodAngle.put(8.0, 0.24); // Extrapolated by Gemini
        hubTable.hoodAngle.put(10.0, 0.28); // Max height

        hubTable.flywheelSpeed.put(1.0, 185.0);
        hubTable.flywheelSpeed.put(2.0, 200.0);
        hubTable.flywheelSpeed.put(3.0, 220.0);
        hubTable.flywheelSpeed.put(4.0, 236.0);
        hubTable.flywheelSpeed.put(5.0, 255.0);
        hubTable.flywheelSpeed.put(6.0, 290.0);
        hubTable.flywheelSpeed.put(8.0, 310.0); // Extrapolated by Gemini
        hubTable.flywheelSpeed.put(10.0, 350.0); // Extrapolated by Gemini

        // Map generated by Gemini with reference point
        hubTable.timeOfFlight.put(1.0, 0.34);
        hubTable.timeOfFlight.put(2.0, 0.63);
        hubTable.timeOfFlight.put(3.0, 0.85);
        hubTable.timeOfFlight.put(3.56, 0.96); // Reference point
        hubTable.timeOfFlight.put(4.0, 1.04);
        hubTable.timeOfFlight.put(5.0, 1.19);
        hubTable.timeOfFlight.put(6.0, 1.31);
        hubTable.timeOfFlight.put(8.0, 1.58);
        hubTable.timeOfFlight.put(10.0, 1.72);
        hubTable.timeOfFlight.put(12.0, 2.25);



        /* *****PASSING***** */
        passingTable.hoodAngle.put(1.0, 0.1);
        passingTable.hoodAngle.put(5.0, 0.2);
        passingTable.hoodAngle.put(8.0, 0.28);

        passingTable.flywheelSpeed.put(1.0, 175.0);
        passingTable.flywheelSpeed.put(4.0, 225.0);
        passingTable.flywheelSpeed.put(8.0, 355.0);
        passingTable.flywheelSpeed.put(12.0, 480.0);

        // Estimated Time of Flight for Passing by Gemini
        passingTable.timeOfFlight.put(1.0, 0.28);
        passingTable.timeOfFlight.put(4.0, 0.82);
        passingTable.timeOfFlight.put(8.0, 1.45);
        passingTable.timeOfFlight.put(12.0, 2.05);
    }
}
