package lib.ballistic;

import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;

public class CommonLookupTable {
    public record ShotTable (
        /** Meters away from hub to hood angle in radians */
        InterpolatingDoubleTreeMap hoodAngle,
        /** Meters away from hub to flywheel speed in radians per second */
        InterpolatingDoubleTreeMap flywheelSpeed,
        /** Time in seconds to shoot to the hub based on distance in meters */
        InterpolatingDoubleTreeMap timeOfFlight
    ) {
        public ShotTable() {
            this(new InterpolatingDoubleTreeMap(), new InterpolatingDoubleTreeMap(), new InterpolatingDoubleTreeMap());
        }
    }

    /** Table containing shooting params for the hub */
    public static final ShotTable hubTable = new ShotTable();
    /** Table containing shooting params for passing */
    public static final ShotTable passingTable = new ShotTable();
    
    static {
        /* *****HUB***** */
        hubTable.hoodAngle.put(1.0, 0.0);
        hubTable.hoodAngle.put(2.0, 0.05);
        hubTable.hoodAngle.put(3.0, 0.09);
        hubTable.hoodAngle.put(4.0, 0.12);
        hubTable.hoodAngle.put(5.0, 0.14);
        hubTable.hoodAngle.put(6.0, 0.17); // Extrapolated by Gemini
        hubTable.hoodAngle.put(8.0, 0.23); // Extrapolated by Gemini

        hubTable.flywheelSpeed.put(1.0, 184.0);
        hubTable.flywheelSpeed.put(2.0, 193.0);
        hubTable.flywheelSpeed.put(2.3, 200.0);
        hubTable.flywheelSpeed.put(2.7, 215.0);
        hubTable.flywheelSpeed.put(3.0, 218.0);
        hubTable.flywheelSpeed.put(4.0, 236.0);
        hubTable.flywheelSpeed.put(5.0, 263.0);
        hubTable.flywheelSpeed.put(6.0, 276.0); // Extrapolated by Gemini
        hubTable.flywheelSpeed.put(8.0, 309.0); // Extrapolated by Gemini
        
        // Map generated by Gemini with reference point
        hubTable.timeOfFlight.put(1.0, 0.36);
        hubTable.timeOfFlight.put(2.0, 0.68);
        hubTable.timeOfFlight.put(3.0, 0.9);
        hubTable.timeOfFlight.put(3.56, 1.0); // Reference point
        hubTable.timeOfFlight.put(4.0, 1.14);
        hubTable.timeOfFlight.put(5.0, 1.29);
        hubTable.timeOfFlight.put(6.0, 1.4);
        hubTable.timeOfFlight.put(8.0, 1.7);


        /* *****PASSING***** */
        passingTable.hoodAngle.put(1.0, 0.05);
        passingTable.hoodAngle.put(5.0, 0.1);
        passingTable.hoodAngle.put(8.0, 0.18);
        passingTable.hoodAngle.put(12.0, 0.25);

        passingTable.flywheelSpeed.put(1.0, 190.0);
        passingTable.flywheelSpeed.put(4.0, 230.0);
        passingTable.flywheelSpeed.put(8.0, 290.0);
        passingTable.flywheelSpeed.put(12.0, 425.0);

        // Estimated Time of Flight for Passing by Gemini
        passingTable.timeOfFlight.put(1.0, 0.28);
        passingTable.timeOfFlight.put(4.0, 0.82);
        passingTable.timeOfFlight.put(8.0, 1.45);
        passingTable.timeOfFlight.put(12.0, 2.05);
    }
}
